from django.db import models

class PanasUserInfo(models.Model):
    username = models.CharField(max_length=30)
    completed = models.BooleanField(default=False)
    interested1 =  models.IntegerField(default=0)
    distressed1 = models.IntegerField(default=0)
    excited1 = models.IntegerField(default=0)
    upset1 = models.IntegerField(default=0)
    strong1 = models.IntegerField(default=0)
    guilty1 = models.IntegerField(default=0)
    scared1 = models.IntegerField(default=0)
    hostile1 = models.IntegerField(default=0)
    enthusiastic1 = models.IntegerField(default=0)
    proud1 = models.IntegerField(default=0)
    irratible1 = models.IntegerField(default=0)
    alert1 = models.IntegerField(default=0)
    ashamed1 = models.IntegerField(default=0)
    inspired1 = models.IntegerField(default=0)
    nervous1 = models.IntegerField(default=0)
    determined1 = models.IntegerField(default=0)
    attentive1 = models.IntegerField(default=0)
    jittery1 = models.IntegerField(default=0)
    active1 = models.IntegerField(default=0)
    afraid1 = models.IntegerField(default=0)
    
    interested2 =  models.IntegerField(default=0)
    distressed2 = models.IntegerField(default=0)
    excited2 = models.IntegerField(default=0)
    upset2 = models.IntegerField(default=0)
    strong2 = models.IntegerField(default=0)
    guilty2 = models.IntegerField(default=0)
    scared2 = models.IntegerField(default=0)
    hostile2 = models.IntegerField(default=0)
    enthusiastic2 = models.IntegerField(default=0)
    proud2 = models.IntegerField(default=0)
    irratible2 = models.IntegerField(default=0)
    alert2 = models.IntegerField(default=0)
    ashamed2 = models.IntegerField(default=0)
    inspired2 = models.IntegerField(default=0)
    nervous2 = models.IntegerField(default=0)
    determined2 = models.IntegerField(default=0)
    attentive2 = models.IntegerField(default=0)
    jittery2 = models.IntegerField(default=0)
    active2 = models.IntegerField(default=0)
    afraid2 = models.IntegerField(default=0)
